### ISSUE TITLE
crash on launch without any args (linux and others)

### ISSUE THREAD

**Issue by Uramekus** [allkern/psx#5]
i did a bisect and since 086b9204604757393f779e614e40aeb5e7e2e969 just running it instantly crashes

will only reproduce with a settings.toml not pointing to a bios

**Comment by supaplextor** [comment]
<pre><code>supaplex@wiseguy:~/ssd/src/supaplextor/psxe$ ./bin/psxe 
psx: info  frontend/config.c: Parsing settings file...
psx: info  frontend/config.c: Settings file parsed. PSXE version: 32a93c23fdcc0a4367506f96537a2dbe14c5d243
free(): invalid pointer
Aborted (core dumped)
supaplex@wiseguy:~/ssd/src/supaplextor/psxe$ gdb ./bin/psxe 
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/psxe...
(gdb) run
Starting program: /home/supaplex/ssd/src/supaplextor/psxe/bin/psxe 

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /lib/x86_64-linux-gnu/libSDL2-2.0.so.0
[Thread debugging using libthread_db enabled]                                                                                                                                                       
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Downloading separate debug info for /lib/x86_64-linux-gnu/libasound.so.2
Downloading separate debug info for /lib/x86_64-linux-gnu/libpulse.so.0                                                                                                                             
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libpulse.so.0                                                                                                            
Downloading separate debug info for /lib/x86_64-linux-gnu/libpulse.so.0
Downloading separate debug info for /lib/x86_64-linux-gnu/libsamplerate.so.0                                                                                                                        
Downloading separate debug info for /lib/x86_64-linux-gnu/libX11.so.6                                                                                                                               
Downloading separate debug info for /lib/x86_64-linux-gnu/libXext.so.6                                                                                                                              
Downloading separate debug info for /lib/x86_64-linux-gnu/libXcursor.so.1                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libXi.so.6                                                                                                                                
Downloading separate debug info for /lib/x86_64-linux-gnu/libXfixes.so.3                                                                                                                            
Downloading separate debug info for /lib/x86_64-linux-gnu/libXrandr.so.2                                                                                                                            
Downloading separate debug info for /lib/x86_64-linux-gnu/libXss.so.1                                                                                                                               
Downloading separate debug info for /lib/x86_64-linux-gnu/libdrm.so.2                                                                                                                               
Downloading separate debug info for /lib/x86_64-linux-gnu/libgbm.so.1                                                                                                                               
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgbm.so.1                                                                                                              
Downloading separate debug info for /lib/x86_64-linux-gnu/libgbm.so.1
Downloading separate debug info for /lib/x86_64-linux-gnu/libwayland-egl.so.1                                                                                                                       
Downloading separate debug info for /lib/x86_64-linux-gnu/libwayland-client.so.0                                                                                                                    
Downloading separate debug info for /lib/x86_64-linux-gnu/libwayland-cursor.so.0                                                                                                                    
Downloading separate debug info for /lib/x86_64-linux-gnu/libxkbcommon.so.0                                                                                                                         
Downloading separate debug info for /lib/x86_64-linux-gnu/libdecor-0.so.0                                                                                                                           
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-16.1.so                                                                                    
Downloading separate debug info for /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-16.1.so
Downloading separate debug info for /lib/x86_64-linux-gnu/libdbus-1.so.3                                                                                                                            
Downloading separate debug info for /lib/x86_64-linux-gnu/libxcb.so.1                                                                                                                               
Downloading separate debug info for /lib/x86_64-linux-gnu/libXrender.so.1                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libexpat.so.1                                                                                                                             
Downloading separate debug info for /lib/x86_64-linux-gnu/libffi.so.8                                                                                                                               
Downloading separate debug info for /lib/x86_64-linux-gnu/libsndfile.so.1                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libX11-xcb.so.1                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libasyncns.so.0                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libapparmor.so.1                                                                                                                          
Downloading separate debug info for /lib/x86_64-linux-gnu/libXau.so.6                                                                                                                               
Downloading separate debug info for /lib/x86_64-linux-gnu/libXdmcp.so.6                                                                                                                             
Downloading separate debug info for /lib/x86_64-linux-gnu/libFLAC.so.12                                                                                                                             
Downloading separate debug info for /lib/x86_64-linux-gnu/libvorbis.so.0                                                                                                                            
Downloading separate debug info for /lib/x86_64-linux-gnu/libvorbisenc.so.2                                                                                                                         
Downloading separate debug info for /lib/x86_64-linux-gnu/libopus.so.0                                                                                                                              
Downloading separate debug info for /lib/x86_64-linux-gnu/libogg.so.0                                                                                                                               
Downloading separate debug info for /lib/x86_64-linux-gnu/libmpg123.so.0                                                                                                                            
Downloading separate debug info for /lib/x86_64-linux-gnu/libmp3lame.so.0                                                                                                                           
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libcap.so.2                                                                                                              
Downloading separate debug info for /lib/x86_64-linux-gnu/libbsd.so.0
Downloading separate debug info for /lib/x86_64-linux-gnu/libmd.so.0                                                                                                                                
psx: info  frontend/config.c: Parsing settings file...                                                                                                                                              
psx: info  frontend/config.c: Settings file parsed. PSXE version: 32a93c23fdcc0a4367506f96537a2dbe14c5d243
Downloading separate debug info for /lib/x86_64-linux-gnu/libudev.so.1
Downloading separate debug info for /lib/x86_64-linux-gnu/libGL.so.1                                                                                                                                
Downloading separate debug info for /lib/x86_64-linux-gnu/libGLdispatch.so.0                                                                                                                        
Downloading separate debug info for /lib/x86_64-linux-gnu/libGLX.so.0                                                                                                                               
Downloading separate debug info for /lib/x86_64-linux-gnu/libGLX_mesa.so.0                                                                                                                          
Downloading separate debug info for /lib/x86_64-linux-gnu/libgallium-25.0.7-0ubuntu0.24.04.2.so                                                                                                     
Downloading separate debug info for /lib/x86_64-linux-gnu/libxcb-glx.so.0                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libXxf86vm.so.1                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libxcb-shm.so.0                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libxcb-dri3.so.0                                                                                                                          
Downloading separate debug info for /lib/x86_64-linux-gnu/libxcb-present.so.0                                                                                                                       
Downloading separate debug info for /lib/x86_64-linux-gnu/libxcb-xfixes.so.0                                                                                                                        
Downloading separate debug info for /lib/x86_64-linux-gnu/libLLVM.so.20.1                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libz.so.1                                                                                                                                 
Downloading separate debug info for /lib/x86_64-linux-gnu/libsensors.so.5                                                                                                                           
Downloading separate debug info for /lib/x86_64-linux-gnu/libxcb-randr.so.0                                                                                                                         
Downloading separate debug info for /lib/x86_64-linux-gnu/libxcb-sync.so.1                                                                                                                          
Downloading separate debug info for /lib/x86_64-linux-gnu/libxshmfence.so.1                                                                                                                         
Downloading separate debug info for /lib/x86_64-linux-gnu/libelf.so.1                                                                                                                               
Downloading separate debug info for /lib/x86_64-linux-gnu/libdrm_amdgpu.so.1                                                                                                                        
Downloading separate debug info for /lib/x86_64-linux-gnu/libdrm_intel.so.1                                                                                                                         
Downloading separate debug info for /lib/x86_64-linux-gnu/libstdc++.so.6                                                                                                                            
Downloading separate debug info for /lib/x86_64-linux-gnu/libgcc_s.so.1                                                                                                                             
Downloading separate debug info for /lib/x86_64-linux-gnu/libedit.so.2                                                                                                                              
Downloading separate debug info for /lib/x86_64-linux-gnu/libxml2.so.2                                                                                                                              
Downloading separate debug info for /lib/x86_64-linux-gnu/libpciaccess.so.0                                                                                                                         
Downloading separate debug info for /lib/x86_64-linux-gnu/libtinfo.so.6                                                                                                                             
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libtinfo.so.6                                                                                                            
Downloading separate debug info for /lib/x86_64-linux-gnu/libtinfo.so.6
Downloading separate debug info for /lib/x86_64-linux-gnu/libicuuc.so.74                                                                                                                            
Downloading separate debug info for /lib/x86_64-linux-gnu/libicudata.so.74                                                                                                                          
[New Thread 0x7fffe8abe6c0 (LWP 19974)]                                                                                                                                                             
[New Thread 0x7fffe3fff6c0 (LWP 19975)]
[Thread 0x7fffe3fff6c0 (LWP 19975) exited]
[New Thread 0x7fffe3fff6c0 (LWP 19976)]
[New Thread 0x7fffe2ffc6c0 (LWP 19977)]
[New Thread 0x7fffeb0d16c0 (LWP 19978)]
[New Thread 0x7fffe27fb6c0 (LWP 19979)]
Memory Card support is disabled
Memory Card support is disabled

Thread 1 "psxe" received signal SIGSEGV, Segmentation fault.
psx_bus_read32 (bus=0x0, addr=0) at psx/bus.c:47
47          HANDLE_READ(bios, 32);
(gdb) where
#0  psx_bus_read32 (bus=0x0, addr=0) at psx/bus.c:47
#1  0x00005555555714f7 in psx_cpu_cycle (cpu=0x555555593470) at psx/cpu.c:246
#2  psx_update (psx=0x555555593120) at psx/psx.c:28
#3  0x00005555555586c8 in main (argc=<optimized out>, argv=<optimized out>) at frontend/main.c:106
</code></pre>

**Comment by ofeeg** [comment]
>``` [New Thread 0x7fffe27fb6c0 (LWP 19979)]
> Memory Card support is disabled
> Memory Card support is disabled
> 
> Thread 1 "psxe" received signal SIGSEGV, Segmentation fault.
> psx_bus_read32 (bus=0x0, addr=0) at psx/bus.c:47
> 47          HANDLE_READ(bios, 32);
> (gdb) where
> #0  psx_bus_read32 (bus=0x0, addr=0) at psx/bus.c:47
> #1  0x00005555555714f7 in psx_cpu_cycle (cpu=0x555555593470) at psx/cpu.c:246
> #2  psx_update (psx=0x555555593120) at psx/psx.c:28
> #3  0x00005555555586c8 in main (argc=, argv=) at frontend/main.c:106
> ```

I get the same error. Consistently crashes at the same area: 


```psx: info  frontend/config.c: Parsing settings file...
psx: info  frontend/config.c: Settings file parsed. PSXE version: 
[New Thread 0x7fffee0ff6c0 (LWP 19107)]
[New Thread 0x7fffed76f6c0 (LWP 19108)]
[New Thread 0x7fffecddf6c0 (LWP 19109)]
Memory Card support is disabled
Memory Card support is disabled

Thread 1 "psxe" hit Breakpoint 2, psx_bus_read32 (bus=<optimized out>, addr=<optimized out>) at psx/bus.c:47

(gdb) step

Thread 4 "SDLAudioP2" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffecddf6c0 (LWP 19109)]
0x000055555558030f in psx_spu_update_cdda_buffer (spu=0x5555555945d0, buf=0x5555555957a4) at psx/dev/spu.c:716
Temporary breakpoint 3 at 0x5555555802e0: file psx/dev/spu.c, line 716.
(gdb) Continuing at 0x5555555802e0.
[Switching to Thread 0x7ffff715e740 (LWP 19103)]

Thread 1 "psxe" hit Breakpoint 2, psx_bus_read32 (bus=<optimized out>, addr=<optimized out>) at psx/bus.c:47
```
